name: Spring CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 실행 권한
        run: chmod +x gradlew

      - name: 빌드 및 테스트
        run: ./gradlew build

      - name: JAR 파일 업로드
        uses: actions/upload-artifact@v4
        with:
          name: spring-app
          path: build/libs/*.jar